removed growl from non darwin (ruby) area.
growl notifications are only sent after completion and when syncing first starts

diff --git a/bin/doubledown b/bin/doubledown
--- a/bin/doubledown
+++ b/bin/doubledown
@@ -27,9 +27,6 @@ do
 done
 shift $(($OPTIND - 1))
 
-env growlnotify -h > /dev/null 2> /dev/null
-has_growl=$?
-
 # Resort to Ruby because `readlink`(1) doesn't have `-f` on OS X.
 if [ "$(uname -s)" = "Darwin" ]
 then
@@ -66,20 +63,12 @@ then
 
 	[ -n "$IDENTITY" ] && ssh-add "$IDENTITY" || \
 	[ -n "$(ssh-add -L)" ] || ssh-add || {
-		if [ "$has_growl" == "0" ] ; then
-		    growlnotify "# [doubledown] no SSH identity found" >&2
-		else
-			echo "# [doubledown] no SSH identity found" >&2
-		fi
+		echo "# [doubledown] no SSH identity found" >&2
 		exit 1
 	}
 
 else
-	if [ "$has_growl" == "0" ] ; then
-	    growlnotify "# [doubledown] ssh-agent not found in your PATH" >&2
-	else
-		echo "# [doubledown] ssh-agent not found in your PATH" >&2
-	fi
+	echo "# [doubledown] ssh-agent not found in your PATH" >&2
 	exit 1
 fi
 
@@ -89,18 +78,10 @@ if which rsync >/dev/null
 then
 	#echo "# [doubledown] syncing baseline from remote" >&2
 	#rsync -azR --ignore-existing "$USER@$SERVER:$REMOTE/./" "$LOCAL"
-	if [ "$has_growl" == "0" ] ; then
-	    growlnotify "# [doubledown] syncing local changes to remote" >&2
-	else
-		echo "# [doubledown] syncing local changes to remote" >&2
-	fi
+	echo "# [doubledown] syncing local changes to remote" >&2
 	rsync $EXCLUDES $PRETEND -azR "$LOCAL/./" "$USER@$SERVER:$REMOTE"
 else
-	if [ "$has_growl" == "0" ] ; then
-	    growlnotify "# [doubledown] rsync not found in your PATH" >&2
-	else
-		echo "# [doubledown] rsync not found in your PATH" >&2
-	fi
+	echo "# [doubledown] rsync not found in your PATH" >&2
 	exit 1
 fi
 
@@ -113,10 +94,6 @@ elif [ "$(uname -s)" = "Linux" ]
 then
 	exec doubledown-inotify "$@"
 else
-	if [ "$has_growl" == "0" ] ; then
-	    growlnotify "# [doubledown] unsupported operating system" >&2
-	else
-		echo "# [doubledown] unsupported operating system" >&2
-	fi
+	echo "# [doubledown] unsupported operating system" >&2
 	exit 1
 fi
